name = "renewal"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间配置
[[kv_namespaces]]
binding = "SUBSCRIPTIONS_KV"
id = "55a0cc019d544671b6c14123810847ea"

# 定时任务配置 - 每天早上8点检查
[triggers]
crons = ["0 8 * * *"]

# 环境变量（可选，也可以在 Cloudflare Dashboard 中设置）
[vars]
ENVIRONMENT = "production"
